# Generated by Django 2.0 on 2018-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahrefs', '0002_ahrefsbacklinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahrefsbacklinks',
            name='first_seen',
            field=models.DateTimeField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ahrefsbacklinks',
            name='last_visited',
            field=models.DateTimeField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ahrefsbacklinks',
            name='prev_visited',
            field=models.DateTimeField(default=0, max_length=255, null=True),
        ),
    ]
